#!/usr/bin/env bash
# |usage.jdx.dev|
# flag "-f --force" help="Overwrite existing <file>"
# flag "-u --user <user>" help="User to run as"
# arg "<file>" help="The file to write" default="file.txt"
# |usage.jdx.dev|

# mise description="This is a test build script"
# mise depends=["lint", "build"]
# mise sources=[".test-tool-versions"]
# mise outputs=["$MISE_PROJECT_ROOT/test/test-build-output.txt"]
# mise env={TEST_BUILDSCRIPT_ENV_VAR = "VALID"}
# mise dir="{{config_root}}"

set -euxo pipefail
cd "$MISE_PROJECT_ROOT" || exit 1
echo "running test-build script"
echo "TEST_BUILDSCRIPT_ENV_VAR: $TEST_BUILDSCRIPT_ENV_VAR" >test/test-build-output.txt
echo "ARGS:" "$@"
